# Generated by Django 3.1.1 on 2020-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ten sach')),
                ('author', models.CharField(max_length=255, verbose_name='Tac gia')),
                ('publisher', models.CharField(max_length=255, null=True, verbose_name='Nha xuat ban')),
                ('year', models.IntegerField(null=True, verbose_name='Nam xuat ban')),
                ('cost', models.IntegerField(verbose_name='Gia')),
            ],
        ),
    ]
